version: '3.9'  # versi칩n de Docker Compose

services:
  web:  # Nombre 
    build: .  
    ports:
      - "5000:5000"  # Mapea el puerto 5000 del contenedor al puerto 5000 de la m치quina
    volumes:
      - .:/app # Monta el directorio actual en el directorio /app del contenedor
    environment:
      - FLASK_APP=lab.py # Indica el nombre del archivo de la aplicaci칩n Flask
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0 # ejecutar la aplicaci칩n Flask
